exports.characters = require('./routes/character')
exports.guilds = require('./routes/guilds')
exports.highscores = require('./routes/highscores')
exports.houses = require('./routes/houses')
exports.news = require('./routes/news')
exports.worlds = require('./routes/worlds')